module.exports = {
  STATE_EMPTY: 0,
  STATE_BLACK: 1,
  STATE_WHITE: 2,
  STATE_REVERSE: 3,     // Not a real state
  STATE_BLACK_KING: 4,
  STATE_WHITE_KING: 5,
  OPTION_UP: 0,
  OPTION_DOWN: 1,
  OPTION_LEFT: 2,
  OPTION_RIGHT: 3,
  OPTION_UP_LEFT: 4,
  OPTION_UP_RIGHT: 5,
  OPTION_DOWN_LEFT: 6,
  OPTION_DOWN_RIGHT: 7,
};
